### ISSUE TITLE
dropbox: Fix URL for maillist

### ISSUE THREAD

**Issue by rffontenelle** [yan12125/aur#14]
Your last comment in [dropbox's AUR page](https://aur.archlinux.org/pkgbase/dropbox) before disabling comment notifications mentions [arch-general](https://lists.archlinux.org/listinfo/arch-general) mail list, however AUR packages should be discussed in [aur-general](https://lists.archlinux.org/listinfo/aur-general) as far as I know. Wouldn't it be best to use the latter one ?

**Comment by yan12125** [comment]
Good point, thanks! I've changed that.
