### ISSUE TITLE
Increase webkit make threads based on cpu threads

### ISSUE THREAD

**Issue by UncleSlug** [yan12125/aur#15]
Is there a reason why the default threads for make is 1? Why not use the same number as the processor, something like:
<pre><code>$(cat /proc/cpuinfo | grep processor | wc -l)</pre></code>
I think something like this would benefit the large majority of people, and the minority could still add more to rice, or down to something like 1 if they have an obscure setup.

Then people like me, who installed it as a dependency for something else via an AUR helper and didn't read the PKGBUILD, don't get an hour or more into before thinking, why is this taking so long and stick it out with the one thread. 👍

**Comment by yan12125** [comment]
Thanks for the suggestion. I didn't enable parallel building for some (minor) issues:

* I was already tired after fixing enchant problems
* My primary building machine has only one core. I can't test if parallel build breaks things or not

I'll try to find an Arch machine with multiple cores to test it. In the mean time, could you check if fdb14ca1474fce95fbec5a7b2f279914baadcf20 works for you?

**Comment by yan12125** [comment]
Oh, [enchant-2](https://www.archlinux.org/todo/enchant-221-rebuild/) comes earlier than I expected. I've pushed the enchant-2 fix along with this one. Please tell me if things are broken.

**Comment by yan12125** [comment]
Sorry for pushing to AUR without testing. It turns out that using the number of CPU threads is infeasible. I've reverted my latest change.

@UncleSlug: See the commit message of 238378e1f18da3157cf0dda26f0d01dcf45723e1 for details.
