### ISSUE TITLE
dropbox: Missing dependencies

### ISSUE THREAD

**Issue by mettke** [yan12125/aur#16]
I have executed ldd on the different dropbox elf files and there are a few dependencies missing: 

```
libXxf86vm.so.1 libXdamage.so.1 libXfixes.so.3 libXrender.so.1 libXcomposite.so.1 libfontconfig.so.1 libfreetype.so.6
```
```bash
ldd /opt/dropbox/libGL.so.1
	libXxf86vm.so.1 => not found
	libXdamage.so.1 => not found
	libXfixes.so.3 => not found

ldd /opt/dropbox/libQt5WebKit.so.5
	libXrender.so.1 => not found
	libXcomposite.so.1 => not found

ldd /opt/dropbox/libQt5XcbQpa.so.5
	libfontconfig.so.1 => not found
	libfreetype.so.6 => not found
```

namcap returns even more dependencies but most of them seem to be incorrect as they are in the Dropbox package itself. The ones in the upper list, however, are required and not getting installed by default.

The libraries can be found in:

* [libxxf86vm](https://www.archlinux.org/packages/extra/x86_64/libxxf86vm/)
* [libxdamage](https://www.archlinux.org/packages/extra/x86_64/libxdamage/)
* [libxfixes](https://www.archlinux.org/packages/extra/x86_64/libxfixes/)
* [libxrender](https://www.archlinux.org/packages/extra/x86_64/libxrender/)
* [libxcomposite](https://www.archlinux.org/packages/extra/x86_64/libxcomposite/)
* [fontconfig](https://www.archlinux.org/packages/extra/x86_64/fontconfig/)
* [freetype2](https://www.archlinux.org/packages/extra/x86_64/freetype2/)

Thanks for supporting

**Comment by yan12125** [comment]
Thanks. Will look into this.

**Comment by yan12125** [comment]
Fixed! Some dependencies are already covered by other dependencies (e.g. libxfixes is already a dependency of libxcomposite), and namcap will complain if I list them, so I skip them. If one day things are changed, feel free to drop a comment and ping me.

Note to myself: patching namcap to detect real dependencies https://github.com/yan12125/aur/blob/master/dropbox/namcap-dropbox.patch
