### ISSUE TITLE
Dropbox: PKGBUILD contains wrong SHA265SUMS

### ISSUE THREAD

**Issue by Dargmuesli** [yan12125/aur#18]
For me a simpe `pacaur -S dropbox` fails at `Validating source files with sha256sums` for files `"dropbox.desktop" "terms.txt" "dropbox.service" "dropbox@.service"`. Am I doing something wrong?

**Comment by Dargmuesli** [comment]
Regarding CRLF: I had set up my .gitconfig incorrectly.

**Comment by yan12125** [comment]
Could you remove the pacaur cache (~/.cache/pacaur/dropbox IIRC) and try again?

**Comment by Dargmuesli** [comment]
Oh, that fixed it indeed. Sorry for the hassle.

**Comment by yan12125** [comment]
No problem :)
