### ISSUE TITLE
dropbox: unrecognized !upx in the options array

### ISSUE THREAD

**Issue by Ghotrix** [yan12125/aur#20]
Make failes due to unrecognized element !upx in the options array of the PKGBUILD.

**Comment by yan12125** [comment]
Could you paste the command you use and the output? I've never got errors about upx.

**Comment by yan12125** [comment]
Closing as no response for a long time. Feel free to leave comments below for any further discussions and I'll reopen this.

**Comment by Ghotrix** [comment]
yaourt dropbox
...
==> Building and installing package
==> ERROR: options array contains unknown option '!upx'

==> ERROR: An unknown error has occurred. Exiting...
==> ERROR: Makepkg was unable to build dropbox.
==> Restart building dropbox ? [y/N]

**Comment by yan12125** [comment]
I guess you're using something like pacman-git? Indeed upx support is removed...

https://git.archlinux.org/pacman.git/commit/?id=1a29744d0da8aa945b96b234574e0d5c80f13b62

**Comment by yan12125** [comment]
Fixed. Thanks for the report!

**Comment by Ghotrix** [comment]
Yep, needed to switch from standard pacman because someone added localized (Y/n) to the dialogs. It was a headache to switch layouts 100 times when I needed something new installed.
